// Generated by Python-to-Signum Compiler
#pragma maxAuxVars 5
#pragma maxConstVars 5
#program name crowdfund
// String constants for return values (map long strings to codes)
// 'withdrawn' -> 1, 'ready' -> 2, 'locked' -> 3
long campaign_active;
long contribution_amount;
long contributor;
long current_block;
long current_contribution;
long deadline_block;
long goal_amount;
long new_contribution;
long owner;
long total_raised;
void main() {
    contribution_amount = 0;
    contributor = 0;
    current_block = 0;
    current_contribution = 0;
    new_contribution = 0;
    owner = 0;
    owner = getCreator();
    goal_amount = 0;
    deadline_block = 0;
    total_raised = 0;
    campaign_active = 1;
}
long setup_campaign(long param_goal, long duration_blocks) {
    if ((getCreator() == owner)) {
        goal_amount = param_goal;
        current_block = getCurrentBlockheight();
        deadline_block = (current_block + duration_blocks);
        campaign_active = 1;
        total_raised = 0;
        return 1;
    } else {
        return 0;
    }
}
long contribute() {
    contribution_amount = getNextTx();
    current_block = getCurrentBlockheight();
    if ((campaign_active == 0)) {
        return 0;
    }
    if ((current_block > deadline_block)) {
        campaign_active = 0;
        return 0;
    }
    contributor = getCreator();
    current_contribution = getMapValue(0, contributor);
    new_contribution = (current_contribution + contribution_amount);
    setMapValue(0, contributor, new_contribution);
    total_raised = (total_raised + contribution_amount);
    if ((total_raised >= goal_amount)) {
        campaign_active = 0;
    }
    return 1;
}
long withdraw_refund() {
    current_block = getCurrentBlockheight();
    if ((campaign_active == 0)) {
        return 0;
    }
    if ((current_block <= deadline_block)) {
        return 0;
    }
    contributor = getCreator();
    contribution_amount = getMapValue(0, contributor);
    if ((contribution_amount > 0)) {
        setMapValue(0, contributor, 0);
        return 1;
    } else {
        return 0;
    }
}
long withdraw_funds() {
    current_block = getCurrentBlockheight();
    if ((campaign_active == 1)) {
        return 0;
    }
    if ((getCreator() != owner)) {
        return 0;
    }
    if ((total_raised >= goal_amount)) {
        return 1;
    } else {
        return 0;
    }
}
long get_campaign_status() {
    if ((campaign_active == 1)) {
        return 1;
    } else {
        if ((total_raised >= goal_amount)) {
            return 2;
        } else {
            current_block = getCurrentBlockheight();
            if ((current_block > deadline_block)) {
                return 3;
            }
            return 0;
        }
    }
}