// Generated by Python-to-Signum Compiler
#pragma maxAuxVars 5
#pragma maxConstVars 5
#program name lottery
// String constants for return values (map long strings to codes)
// 'withdrawn' -> 1, 'ready' -> 2, 'locked' -> 3
long buyer;
long current_block;
long draw_block;
long lottery_active;
long owner;
long paid_amount;
long prize_amount;
long random_value;
long refund_amount;
long ticket_number;
long ticket_price;
long total_tickets;
long winner;
long winning_number;
void main() {
    buyer = 0;
    current_block = 0;
    owner = 0;
    paid_amount = 0;
    prize_amount = 0;
    random_value = 0;
    refund_amount = 0;
    ticket_number = 0;
    winning_number = 0;
    owner = getCreator();
    ticket_price = 10;
    total_tickets = 0;
    lottery_active = 1;
    draw_block = 0;
    winner = 0;
}
long start_lottery(long duration_blocks) {
    if ((getCreator() == owner)) {
        current_block = getCurrentBlockheight();
        draw_block = (current_block + duration_blocks);
        lottery_active = 1;
        total_tickets = 0;
        winner = 0;
        return 1;
    } else {
        return 0;
    }
}
long buy_ticket() {
    if ((lottery_active == 0)) {
        return 0;
    }
    current_block = getCurrentBlockheight();
    if ((current_block >= draw_block)) {
        lottery_active = 0;
        return 0;
    }
    paid_amount = getNextTx();
    if ((paid_amount < ticket_price)) {
        return 0;
    }
    buyer = getCreator();
    ticket_number = (total_tickets + 1);
    setMapValue(0, ticket_number, buyer);
    total_tickets = (total_tickets + 1);
    if ((paid_amount > ticket_price)) {
        refund_amount = (paid_amount - ticket_price);
    }
    return 1;
}
long draw_winner() {
    if ((lottery_active == 1)) {
        current_block = getCurrentBlockheight();
        if ((current_block < draw_block)) {
            return 0;
        }
        lottery_active = 0;
    }
    if ((total_tickets == 0)) {
        return 0;
    }
    if ((winner != 0)) {
        return 0;
    }
    random_value = getCurrentBlockheight();
    winning_number = ((random_value % total_tickets) + 1);
    winner = getMapValue(0, winning_number);
    prize_amount = (ticket_price * total_tickets);
    return 1;
}
long get_ticket_count() {
    return total_tickets;
}