// Generated by Python-to-Signum Compiler
#pragma maxAuxVars 5
#pragma maxConstVars 5
#program name multisig
// String constants for return values (map long strings to codes)
// 'withdrawn' -> 1, 'ready' -> 2, 'locked' -> 3
long approval_count;
long current_sender;
long owner1;
long owner2;
long owner3;
long required_signatures;
long tx_amount;
long tx_approved_by_owner1;
long tx_approved_by_owner2;
long tx_approved_by_owner3;
long tx_executed;
long tx_to;
void main() {
    approval_count = 0;
    current_sender = 0;
    owner1 = 0;
    owner1 = getCreator();
    owner2 = 0;
    owner3 = 0;
    required_signatures = 2;
    tx_to = "";
    tx_amount = 0;
    tx_approved_by_owner1 = 0;
    tx_approved_by_owner2 = 0;
    tx_approved_by_owner3 = 0;
    tx_executed = 0;
}
long setup_owners(long owner2_addr, long owner3_addr) {
    if ((getCreator() == owner1)) {
        owner2 = owner2_addr;
        owner3 = owner3_addr;
        return 1;
    } else {
        return 0;
    }
}
long propose_transaction(long param_to, long param_amount) {
    current_sender = getCreator();
    tx_to = param_to;
    tx_amount = param_amount;
    tx_approved_by_owner1 = 0;
    tx_approved_by_owner2 = 0;
    tx_approved_by_owner3 = 0;
    tx_executed = 0;
    if ((current_sender == owner1)) {
        tx_approved_by_owner1 = 1;
    } else {
        if ((current_sender == owner2)) {
            tx_approved_by_owner2 = 1;
        } else {
            if ((current_sender == owner3)) {
                tx_approved_by_owner3 = 1;
            } else {
                return 0;
            }
        }
    }
    return 1;
}
long approve_transaction() {
    current_sender = getCreator();
    if ((tx_executed == 1)) {
        return 0;
    }
    if ((current_sender == owner1)) {
        tx_approved_by_owner1 = 1;
    } else {
        if ((current_sender == owner2)) {
            tx_approved_by_owner2 = 1;
        } else {
            if ((current_sender == owner3)) {
                tx_approved_by_owner3 = 1;
            } else {
                return 0;
            }
        }
    }
    approval_count = ((tx_approved_by_owner1 + tx_approved_by_owner2) + tx_approved_by_owner3);
    if ((approval_count >= required_signatures)) {
        tx_executed = 1;
        return 1;
    }
    return 0;
}
long get_approval_status() {
    approval_count = ((tx_approved_by_owner1 + tx_approved_by_owner2) + tx_approved_by_owner3);
    if ((tx_executed == 1)) {
        return 4;
    } else {
        if ((approval_count >= required_signatures)) {
            return 3;
        } else {
            return approval_count;
        }
    }
}