// Generated by Python-to-Signum Compiler
#pragma maxAuxVars 5
#pragma maxConstVars 5
#program name mytoken
// String constants for return values (map long strings to codes)
// 'withdrawn' -> 1, 'ready' -> 2, 'locked' -> 3
long current_balance;
long current_supply;
long decimals;
long name;
long new_balance;
long new_receiver_balance;
long new_sender_balance;
long new_supply;
long owner;
long receiver_balance;
long sender_addr;
long sender_balance;
long symbol;
long total_supply;
void main() {
    current_balance = 0;
    current_supply = 0;
    new_balance = 0;
    new_receiver_balance = 0;
    new_sender_balance = 0;
    new_supply = 0;
    owner = 0;
    receiver_balance = 0;
    sender_addr = 0;
    sender_balance = 0;
    name = "MyToken";
    symbol = "MTK";
    decimals = 8;
    total_supply = 1000000;
    owner = getCreator();
    setMapValue(0, owner, total_supply);
    setMapValue(0, 100, total_supply);
}
long transfer(long param_to, long amount) {
    sender_addr = getCreator();
    sender_balance = getMapValue(0, sender_addr);
    if ((sender_balance >= amount)) {
        new_sender_balance = (sender_balance - amount);
        setMapValue(0, sender_addr, new_sender_balance);
        receiver_balance = getMapValue(0, param_to);
        new_receiver_balance = (receiver_balance + amount);
        setMapValue(0, param_to, new_receiver_balance);
        return 1;
    } else {
        return 0;
    }
}
long balance_of(long address) {
    // return get();  // Signum function
    return 0;
}
long mint(long param_to, long amount) {
    if ((getCreator() == owner)) {
        current_supply = getMapValue(0, 100);
        new_supply = (current_supply + amount);
        setMapValue(0, 100, new_supply);
        current_balance = getMapValue(0, param_to);
        new_balance = (current_balance + amount);
        setMapValue(0, param_to, new_balance);
        return 1;
    } else {
        return 0;
    }
}
long burn(long amount) {
    sender_addr = getCreator();
    sender_balance = getMapValue(0, sender_addr);
    if ((sender_balance >= amount)) {
        new_balance = (sender_balance - amount);
        setMapValue(0, sender_addr, new_balance);
        current_supply = getMapValue(0, 100);
        new_supply = (current_supply - amount);
        setMapValue(0, 100, new_supply);
        return 1;
    } else {
        return 0;
    }
}