// Generated by Python-to-Signum Compiler
#pragma maxAuxVars 5
#pragma maxConstVars 5
#program name vault
// String constants for return values (map long strings to codes)
// 'withdrawn' -> 1, 'ready' -> 2, 'locked' -> 3
long current_block;
long lock_amount;
long owner;
long release_block;
long remaining;
long remaining_blocks;
long sender_addr;
long withdrawn;
void main() {
    current_block = 0;
    owner = 0;
    remaining = 0;
    remaining_blocks = 0;
    sender_addr = 0;
    owner = getCreator();
    lock_amount = 0;
    release_block = 0;
    withdrawn = 0;
}
long lock(long param_amount, long lock_blocks) {
    sender_addr = getCreator();
    if ((sender_addr == owner)) {
        lock_amount = param_amount;
        current_block = getCurrentBlockheight();
        release_block = (current_block + lock_blocks);
        withdrawn = 0;
        return 1;
    } else {
        return 0;
    }
}
long withdraw() {
    current_block = getCurrentBlockheight();
    if ((withdrawn == 0)) {
        if ((current_block >= release_block)) {
            withdrawn = 1;
            return 1;
        } else {
            remaining_blocks = (release_block - current_block);
            return 0;
        }
    } else {
        return 0;
    }
}
long get_status() {
    current_block = getCurrentBlockheight();
    if ((withdrawn == 1)) {
        return 1;
    } else {
        if ((current_block >= release_block)) {
            return "ready";
        } else {
            remaining = (release_block - current_block);
            return remaining;
        }
    }
}